version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ruby bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - sqlite_data:/rails/db
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    stdin_open: true
    tty: true

volumes:
  bundle:
  sqlite_data: